apiVersion: apps/v1
kind: Deployment
metadata:
  name: classroom-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classroom
  template:
    metadata:
      labels:
        app: classroom
    spec:
      containers:
      - name: classroom-container
        image: mabdullah12/classrooms:latest
        ports:
        - containerPort: 3003
        - containerPort: 8004
