apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
      - name: event-bus-container
        image: mabdullah12/event-bus:latest
        ports:
        - containerPort: 3004
        - containerPort: 8005
